# ref: https://docs.codecov.com/docs/codecovyml-reference
coverage:
  range: 60..80
  round: down
  precision: 2
  status:
    # ref: https://docs.codecov.com/docs/commit-status
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

# Test files aren't important for coverage
ignore:
  - "tests"

# Make comments less noisy
# https://docs.codecov.com/docs/pull-request-comments
comment:
  layout: "condensed_header, condensed_files, condensed_footer"
  hide_project_coverage: TRUE
  require_changes: yes
