[default.extend-words]
mosquitto = "mosquitto"
hda = "hda"
tegde = "tedge"
OT = "OT"
Robocorp = "Robocorp"
Packagecloud = "Packagecloud"
Gemfury = "Gemfury"
JFrog = "JFrog"
gost = "gost"

[default]
extend-ignore-identifiers-re = [
    # ignore hexa data samples
    "[0-9a-fA-F][0-9a-fA-F]"
]

[files]
extend-exclude = [
    "**certificate.txt",
    "**test_root_cert*.txt",
    "**.crl",
    "**.min.js"
]

