[package]
name = "tedge_config_macros"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
camino = { version = "*", features = ["serde1"] }
doku = "0.21.0"
once_cell = "*"
serde = "*"
tedge_config_macros-macro = { path = "macro" }
thiserror = "1.0"
tracing = "*"
url = "*"
