[package]
name = "tedge_uploader_ext"
description = "thin-edge extension adding uploaders"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
async-trait = { workspace = true }
camino = { workspace = true }
log = { workspace = true }
reqwest = { workspace = true, features = ["rustls-tls-native-roots"] }
tedge_actors = { workspace = true }
tedge_utils = { workspace = true }
upload = { workspace = true }

[dev-dependencies]
mockito = { workspace = true }
tedge_test_utils = { workspace = true }
tokio = { workspace = true, default_features = false, features = ["time"] }

[lints]
workspace = true
