[package]
name = "tedge-agent"
description = "tedge-agent interacts with a Cloud Mapper and one or more Software Plugins"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
axum = { workspace = true }
axum-server = { workspace = true }
axum_tls = { workspace = true }
camino = { workspace = true }
certificate = { workspace = true, features = ["reqwest"] }
clap = { workspace = true }
flockfile = { workspace = true }
futures = { workspace = true }
hyper = { workspace = true, features = ["full"] }
lazy_static = { workspace = true }
log = { workspace = true }
path-clean = { workspace = true }
plugin_sm = { workspace = true }
reqwest = { workspace = true }
rustls = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha256 = { workspace = true }
tedge_actors = { workspace = true }
tedge_api = { workspace = true }
tedge_config = { workspace = true }
tedge_config_manager = { workspace = true }
tedge_downloader_ext = { workspace = true }
tedge_file_system_ext = { workspace = true }
tedge_health_ext = { workspace = true }
tedge_log_manager = { workspace = true }
tedge_mqtt_ext = { workspace = true }
tedge_script_ext = { workspace = true }
tedge_signal_ext = { workspace = true }
tedge_uploader_ext = { workspace = true }
tedge_utils = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true, features = ["formatting"] }
tokio = { workspace = true, features = ["rt-multi-thread"] }
tokio-util = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
which = { workspace = true }

[dev-dependencies]
assert-json-diff = { workspace = true }
axum_tls = { workspace = true, features = ["test-helpers"] }
bytes = { workspace = true }
http-body = { workspace = true }
rcgen = { workspace = true }
rustls-pemfile = { workspace = true }
tedge_actors = { workspace = true, features = ["test-helpers"] }
tedge_mqtt_ext = { workspace = true, features = ["test-helpers"] }
tedge_test_utils = { workspace = true }
tempfile = { workspace = true }
test-case = { workspace = true }
tower = { workspace = true }

[lints]
workspace = true
