[package]
name = "upload"
description = "upload manager"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
axum_tls = { workspace = true, features = ["error-matching"] }
backoff = { workspace = true }
camino = { workspace = true }
log = { workspace = true }
mime = { workspace = true }
mime_guess = { workspace = true }
reqwest = { workspace = true, features = [
    "stream",
    "rustls-tls-native-roots",
    "multipart",
] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["fs"] }
tokio-util = { workspace = true, features = ["codec"] }

[dev-dependencies]
anyhow = { workspace = true }
axum = { workspace = true }
futures = { workspace = true }
mockito = { workspace = true }
tedge_test_utils = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true
