[package]
name = "batcher"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
time = "0.3"
tokio = { version = "1.23", features = ["sync", "time"] }

[dev-dependencies]
tokio = { version = "1.23", features = ["rt", "macros"] }
