[package]
name = "batcher"
version = "0.8.1"
authors = ["thin-edge.io team <info@thin-edge.io>"]
edition = "2021"
rust-version = "1.63"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time = "0.3"
tokio = { version = "1.23", features = ["sync", "time"] }

[dev-dependencies]
tokio = { version = "1.23", features = ["rt", "macros"] }
