[package]
name = "batcher"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
async-trait = { workspace = true }
tedge_actors = { workspace = true }
time = { workspace = true }
tokio = { workspace = true, features = ["time"] }

[dev-dependencies]
tedge_actors = { workspace = true, features = ["test-helpers"] }
tokio = { workspace = true, features = ["rt", "macros"] }

[lints]
workspace = true
