[package]
name = "c8y_auth_proxy"
description = "An HTTP proxy to Cumulocity that automatically authenticates incoming requests"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
anyhow = { workspace = true }
axum = { workspace = true, features = ["macros"] }
axum-server = { workspace = true }
c8y_http_proxy = { workspace = true }
camino = { workspace = true }
futures = { workspace = true }
hyper = { workspace = true }
rcgen = { workspace = true }
pin-project = { workspace = true }
reqwest = { workspace = true, features = ["stream"] }
rustls = { workspace = true }
rustls-pemfile = { workspace = true }
tedge_actors = { workspace = true }
tedge_config = { workspace = true }
tedge_config_macros = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "process", "io-util"] }
tokio-rustls = { workspace = true }
tower = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
x509-parser = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
env_logger = { workspace = true }
mockito = { workspace = true }
tedge_http_ext = { workspace = true, features = ["test_helpers" ] }
