name: Build and Deploy to Github Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: Install stable
        uses: dtolnay/rust-toolchain@stable

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: "0.4.18"
          # mdbook-version: 'latest'

      - name: install mdbook-mermaid
        run: cargo install mdbook-mermaid

      - name: install mdbook-linkcheck
        run: cargo install mdbook-linkcheck

      - name: install mdbook-admonish
        run: cargo install mdbook-admonish

      - name: install mdbook-pagetoc
        run: cargo install mdbook-pagetoc

      - name: install mdbook-cmdrun
        run: cargo install mdbook-cmdrun

      - name: Cargo build tedge cli
        run: cargo build --bin tedge

      - name: Update PATH
        run: echo "$PWD/target/debug" >> $GITHUB_PATH

      - name: Run mdbook build
        shell: bash
        run: |
          echo "generating doc for $(tedge --version)"
          cd docs
          mdbook build

      # Blocking deploy till fully ported to docusaurus
      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   if: github.ref == 'refs/heads/main'
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./docs/book/html
      #     destination_dir: html

