name: update-tedge-reference-documents

on:
  # trigger manually
  workflow_dispatch:
  # runs automatically on 00:00 UTC on 1st of every month
  schedule:
  - cron: "0 0 1 * *"

jobs:
    build-tedge-create-ref-docs:
      runs-on: Ubuntu-20.04

      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - run: |
           git config --global user.email "info@thin-edge.io"
           git config --global user.name "Versioneer"

        - name: Retrieve MSRV from workspace Cargo.toml
          id: rust_version
          uses: SebRollen/toml-action@v1.0.2
          with:
            file: Cargo.toml
            field: "workspace.package.rust-version"

        - name: Enable toolchain via github action
          uses: dtolnay/rust-toolchain@master
          with:
            toolchain: ${{ steps.rust_version.outputs.value }}

        - name: Enable cache
          # https://github.com/marketplace/actions/rust-cache
          uses: Swatinem/rust-cache@v2

        - name: Build tedge
          uses: actions-rs/cargo@v1
          # https://github.com/marketplace/actions/rust-cargo
          with:
            command: build
            args: --release -p tedge

        - name: run the update script
          run: ./docs/gen-ref-docs.sh
        - name: Create Pull Request
          uses: peter-evans/create-pull-request@v4
          with:
            commit-message: Create tedge cli reference docs
            delete-branch: true
            title: Create tedge reference docs
            body: Create tedge reference docs
            reviewers: rina23q
            branch: create-pull-request/update-tedge-ref-doc
